---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventoryselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineinventoryselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elemental.cattle.io
  resources:
  - machineregistrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fleet.cattle.io
  resources:
  - bundles
  verbs:
  - '*'
- apiGroups:
  - management.cattle.io
  resources:
  - setting
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - watch
